version: "1.0"

app:
  name: image-generation-frontend
  type: web

runtime:
  node: "18"

build:
  commands:
    # Install dependencies
    - npm install
    # Build React app
    - npm run build

run:
  command: >
    npx serve -s build -l 3000
  port: 3000

env:
  # Backend URL (replace with backend app URL later)
  - name: REACT_APP_BACKEND_URL
    value: "http://localhost:8000"

resources:
  cpu: "2"
  memory: "4Gi"
