# app.yaml

version: "1.0"

app:
  name: image-generation-backend
  type: web

runtime:
  python: "3.10"

build:
  commands:
    # Upgrade pip
    - pip install --upgrade pip
    # Install dependencies
    - pip install -r requirements.txt

run:
  command: >
    uvicorn main:app
    --host 0.0.0.0
    --port 8000
  port: 8000

env:
  # Gemini API key (set this securely in Databricks UI)
  - name: GEMINI_API_KEY
    valueFrom: secret:GEMINI_API_KEY

resources:
  cpu: "4"
  memory: "16Gi"
